src/Entity/Personnage.php
<?php

namespace App\Entity;

use App\Repository\PersonnageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=PersonnageRepository::class)
 */
class Personnage
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * 
     */
    private $nom;

    /****************************** PARTIE CLASSE ******************************/

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $classe; 
    
    /**
     * @ORM\Column(type="array")
     */
    private $specialite = [];
    
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $standard_de_vie;
    
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $avantage_culturel;

    /**
     *@ORM\Column(type="integer")
     */
    private $Admiration;

    /**
     *@ORM\Column(type="integer")
     */
    private $Athletisme;

    /**
     *@ORM\Column(type="integer")
     */
    private $Conscience;

    /**
     *@ORM\Column(type="integer")
     */
    private $Exploration;

    /**
     *@ORM\Column(type="integer")
     */
    private $Chant;

    /**
     *@ORM\Column(type="integer")
     */
    private $Artisanat;

    /**
     *@ORM\Column(type="integer")
     */
    private $Inspiration;

    /**
     *@ORM\Column(type="integer")
     */
    private $Voyage;

    /**
     *@ORM\Column(type="integer")
     */
    private $Perspicacite;

    /**
     *@ORM\Column(type="integer")
     */
    private $Guerison;

    /**
    *@ORM\Column(type="integer")
     */
    private $Courtoisie;

    /**
     *@ORM\Column(type="integer")
     */
    private $Combat;

    /**
    *@ORM\Column(type="integer")
     */
    private $Persuasion;

    /**
    *@ORM\Column(type="integer")
     */
    private $Furtivite;

    /**
    *@ORM\Column(type="integer")
     */
    private $Fouille;

    /**
    *@ORM\Column(type="integer")
     */
    private $Chasse;

    /**
     *@ORM\Column(type="integer")
     */
    private $Enigmes;

    /**
    *@ORM\Column(type="integer")
     */
    private $Conaissances;

   /****************************** PARTIE CLASSE ******************************/

   /****************************** PARTIE ORIGINE ******************************/
   /**
     * @ORM\Column(type="string", length=255)
     */
    private $origine;

     /**
     * @ORM\Column(type="array")
     */
    private $particularite = [];

    /**
     * @ORM\Column(type="integer")
     */
    private $coeur;

    /**
     * @ORM\Column(type="integer")
     */
    private $corps;

    /**
     * @ORM\Column(type="integer")
     */
    private $esprit;


    /****************************** PARTIE ORIGINE ******************************/


    /****************************** PARTIE VOCATION ******************************/

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $vocation;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $competence_favorite;
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $competences_favorites_vocation;

     /**
     * @ORM\Column(type="string", length=255)
     */
    private $part_ombre;

      /**
     * @ORM\Column(type="string", length=255)
     */
    private $traits;

    /**
     * @ORM\OneToMany(targetEntity=Armes::class, mappedBy="personnage")
     */
    private $arme;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="personnages")
     * @ORM\JoinColumn(nullable=false)
     */
    private $joueur;

    /**
     * @ORM\OneToOne(targetEntity=AttributAmeliores::class, mappedBy="personnage", cascade={"persist", "remove"})
     */
    
    private $attributAmeliores;
    /**
     * @ORM\ManyToMany(targetEntity=Partie::class, inversedBy="personnages")
     */
    private $partie;

    /**
     * @ORM\Column(type="integer")
     */
    private $espoir;

    /**
     * @ORM\Column(type="integer")
     */
    private $endurance;

    /**
     * @ORM\Column(type="integer")
     */
    private $vaillance;

    /**
     * @ORM\Column(type="integer")
     */
    private $sagesse;

    /**
     * @ORM\OneToMany(targetEntity=Vertus::class, mappedBy="personnage")
     */
    private $vertus;

    /**
     * @ORM\OneToMany(targetEntity=Recompence::class, mappedBy="personnage")
     */
    private $recompences;

   

    /****************************** PARTIE VOCATION ******************************/


    public function __construct()
    {
        $this->traits = new ArrayCollection();
        $this->vertus = new ArrayCollection();
        $this->recompenses = new ArrayCollection();
        $this->arme = new ArrayCollection();
        $this->partie = new ArrayCollection();
        $this->recompences = new ArrayCollection();
        
       
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getCorps(): ?int
    {
        return $this->corps;
    }

    public function setCorps(int $corps): self
    {
        $this->corps = $corps;

        return $this;
    }

    public function getEsprit(): ?int
    {
        return $this->esprit;
    }

    public function setEsprit(int $esprit): self
    {
        $this->esprit = $esprit;

        return $this;
    }

    public function getStandardDeVie(): ?string
    {
        return $this->standard_de_vie;
    }

    public function setStandardDeVie(string $standard_de_vie): self
    {
        $this->standard_de_vie = $standard_de_vie;

        return $this;
    }


    public function getVocation():  ?string
    {
        return $this->vocation;
    }

    public function setVocation(?string $vocation): self
    {
        $this->vocation = $vocation;

        return $this;
    }
    
    public function getOrigine(): ?string
    {
        return $this->origine;
    }

    public function setOrigine(string $origine): self
    {
        $this->origine = $origine;

        return $this;
    }

    public function getClasse(): ?string
    {
        return $this->classe;
    }

    public function setClasse(string $classe): self
    {
        $this->classe = $classe;

        return $this;
    }

    public function getAvantageCulturel(): ?string
    {
        return $this->avantage_culturel;
    }

    public function setAvantageCulturel(string $avantage_culturel): self
    {
        $this->avantage_culturel = $avantage_culturel;

        return $this;
    }


    public function getSpecialite(): ?array
    {
        return $this->specialite;
    }

    public function setSpecialite(array $specialite): self
    {
        $this->specialite = $specialite;

        return $this;
    }

    public function getParticularite(): ?array
    {
        return $this->particularite;
    }

    public function setParticularite(array $particularite): self
    {
        $this->particularite = $particularite;

        return $this;
    }

    public function getAdmiration(): ?int
    {
        return $this->Admiration;
    }

    public function setAdmiration(string $Admiration): self
    {
        $this->Admiration = $Admiration;

        return $this;
    }

    public function getAthletisme(): ?string
    {
        return $this->Athletisme;
    }

    public function setAthletisme(string $Athletisme): self
    {
        $this->Athletisme = $Athletisme;

        return $this;
    }

    public function getConscience(): ?int
    {
        return $this->Conscience;
    }

    public function setConscience(string $Conscience): self
    {
        $this->Conscience = $Conscience;

        return $this;
    }

    public function getExploration(): ?int
    {
        return $this->Exploration;
    }

    public function setExploration(string $Exploration): self
    {
        $this->Exploration = $Exploration;

        return $this;
    }

    public function getChant(): ?int
    {
        return $this->Chant;
    }

    public function setChant(string $Chant): self
    {
        $this->Chant = $Chant;

        return $this;
    }

    public function getArtisanat(): ?string
    {
        return $this->Artisanat;
    }

    public function setArtisanat(string $Artisanat): self
    {
        $this->Artisanat = $Artisanat;

        return $this;
    }

    public function getInspiration(): ?int
    {
        return $this->Inspiration;
    }

    public function setInspiration(string $Inspiration): self
    {
        $this->Inspiration = $Inspiration;

        return $this;
    }

    public function getVoyage(): ?int
    {
        return $this->Voyage;
    }

    public function setVoyage(string $Voyage): self
    {
        $this->Voyage = $Voyage;

        return $this;
    }

    public function getPerspicacite(): ?int
    {
        return $this->Perspicacite;
    }

    public function setPerspicacite(string $Perspicacite): self
    {
        $this->Perspicacite = $Perspicacite;

        return $this;
    }

    public function getGuerison(): ?int
    {
        return $this->Guerison;
    }

    public function setGuerison(string $Guerison): self
    {
        $this->Guerison = $Guerison;

        return $this;
    }

    public function getCourtoisie(): ?string
    {
        return $this->Courtoisie;
    }

    public function setCourtoisie(string $Courtoisie): self
    {
        $this->Courtoisie = $Courtoisie;

        return $this;
    }

    public function getCombat(): ?string
    {
        return $this->Combat;
    }

    public function setCombat(string $Combat): self
    {
        $this->Combat = $Combat;

        return $this;
    }

src/Controller/PersonnagesController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PersonnagesController extends AbstractController
{
    //#[Route('/personnages', name: 'personnages')]
    /**
     * @Route("/personnages", name="personnages")
     */
    public function index(): Response
    {
        return $this->render('personnages/index.html.twig', [
            'controller_name' => 'PersonnagesController',
        ]);
    }
}

templates/personnage/_delete_form.html.twig
<form method="post" action="{{ path('personnage_delete', {'id': personnage.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ personnage.id) }}">
    <button class="btn">Delete</button>
</form>

templates/personnage/_edit_form.html.twig
<h4>Armes</h4>
{% for arme in armes %}
    {{ include('armes/_delete_form.html.twig') }}
{% endfor %}
<h4>Vertus</h4>
{% for vertu in vertus %}
    {{ include('vertus/_delete_form.html.twig') }}
{% endfor %}
<h4>Recompences</h4>
    {% for recompence in recompences %}
        {{ include('recompence/_delete_form.html.twig') }}
    {% endfor %}

{{ form_start(form, { 'attr' : {'id': 'personnageForm'}}) }}
    {{ form_widget(form) }}
    
    
    <button class="btn btn-outline-dark justify-content-center" type="submit" name="_valid" value="1" >{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/personnage/_form.html.twig
{{ form_start(form, { 'attr' : {'id': 'personnageForm' , 'class' : 'persoForm'}}) }}

    <div class="classeBanniere">
    <h1>Créer votre Personnage</h1>
    

    <div class="start">
        <div class="classe-input">
            {{ form_row(form.nom)}}
            {{ form_row(form.classe)}}
            {{ form_row(form.origine)}}
            {{ form_row(form.vocation)}}
        </div>
        <div class="classe-img">
           <img src="https://media.discordapp.net/attachments/968448853160386591/968932547419598878/bardie.png" width="40%"></img>
        </div>        
    </div>
</div>
<div class="barre"><br><br></div>

    

    <div class="main-content">

    
      
            {% if form.Admiration is defined %}
                <div class="left">
                    <h2>PARTICULARITES</h2>
                    <div class="content">
                        <div class="left-content">
                            {{ form_row(form.Admiration ,{ 'attr': {'class': 'mb-3'}})}}
                            {{ form_row(form.Athletisme, { 'attr': {'class': 'mb-3'}})}}
                            {{ form_row(form.Conscience, { 'attr': {'class': 'mb-3'}})}}
                            {{ form_row(form.Exploration, { 'attr': {'class': 'mb-3'}})}}
                            {{ form_row(form.Chant, { 'attr': {'class': 'mb-3'}})}}
                            {{ form_row(form.Artisanat, { 'attr': {'class': 'mb-3'}})}}
                            {{ form_row(form.Inspiration, { 'attr': {'class': 'mb-3'}})}}
                            {{ form_row(form.Voyage, { 'attr': {'class': 'mb-3'}})}}
                            {{ form_row(form.Perspicacite, { 'attr': {'class': 'mb-3'}})}}
                        </div>
                        <div class="right-content">
                            {{ form_row(form.Guerison, { 'attr': {'class': 'mb-3'}})}}
                            {{ form_row(form.Courtoisie, { 'attr': {'class': 'mb-3'}})}}
                            {{ form_row(form.Combat, { 'attr': {'class': 'mb-3'}})}}
                            {{ form_row(form.Persuasion, { 'attr': {'class': 'mb-3'}})}}
                            {{ form_row(form.Furtivite, { 'attr': {'class': 'mb-3'}})}}
                            {{ form_row(form.Fouille, { 'attr': {'class': 'mb-3'}})}}
                            {{ form_row(form.Chasse, { 'attr': {'class': 'mb-3'}})}}
                            {{ form_row(form.Enigmes, { 'attr': {'class': 'mb-3'}})}}
                            {{ form_row(form.Conaissances, { 'attr': {'class': 'mb-3'}})}}
                        </div>
                    </div>
                </div>
            {% endif %}
        

        
            {% if form.armes is defined %}
            <div class="midle">
                <h2> SPECIALITES </h2>
                <div class="content">
                    <div class="right-content">
                        {{ form_row(form.armes)}}
                        {{ form_row(form.specialites1)}}
                        {{ form_row(form.specialites2)}}
                        {% if form.Particularite is defined %}
                            {{ form_row(form.Particularite)}}
                        {% endif %}
                        {{ form_row(form.attributCorps)}}
                        {% if form.attributCoeur is defined %}
                            {{ form_row(form.attributCoeur)}}
                        {% endif %}
                        {% if form.attributEsprit is defined  %}        
                            {{ form_row(form.attributEsprit)}} 
                        {% endif %}   
                        {% if form.vertus is defined%}
                            {{ form_row(form.vertus)}}
                        {% endif %}  

                        {% if form.competences_favorites_vocation is defined %}
                            {{ form_row(form.competences_favorites_vocation)}}  
                        {% endif %}  

                        {% if form.recompence is defined %}
                           {{ form_row(form.recompence)}}
                        {% endif %}

                        
                        {{ form_row(form.valeurPrincipale)}} 
                    </div>
                    <div class="left-content">
                        {{ form_row(form.standard_de_vie)}}
                        {{ form_row(form.avantage_culturel)}}
                        {% if form.competence_favorite is defined %}
                            {{ form_row(form.competence_favorite)}}
                            {{ form_row(form.endurance)}}
                            {{ form_row(form.espoir)}}
                            {{ form_row(form.corps)}}
                            {{ form_row(form.esprit)}} 
                        {% endif %}
                        {% if form.Particularite is defined %}
                            {{ form_row(form.coeur)}} 
                        {% endif %}
                        {% if form.traits is defined %}
                            {{ form_row(form.part_ombre)}}
                            {{ form_row(form.traits)}}
                            
                        {% endif %} 
                    </div>
                </div>
            </div>
            {% endif %}
    </div>
    <div class="end">
        <button class="validation" type="submit" name="_valid" value="1" >{{ button_label|default('Enregistrer') }}</button>
    </div>
{{ form_end(form) }}

templates/personnage/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mofifier ce personnage{% endblock %}

{% block body %}
    <h1>Modifier ce personnage</h1>
        
    {{ include('personnage/_edit_form.html.twig', {'button_label': 'Update'}) }}
{% endblock %}

templates/personnage/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Personnage index{% endblock %}

{% block body %}
    <h1>Page Perso</h1>
 
{% endblock %}

templates/personnage/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau Personnage{% endblock %}

{% block body %}

    <div class="col" >
       
        <div class="content-form">
            {{ include('personnage/_form.html.twig') }}
        </div>
        <div class="loader">
            <div class="rotate-circle"></div>
        </div>
    </div>
{% endblock %}

templates/personnage/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Personnage{% endblock %}

{% block body %}
    <h1>Personnage</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ personnage.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ personnage.nom }}</td>
            </tr>
            <tr>
                <th>Corps</th>
                <td>{{ personnage.corps }}</td>
            </tr>
            <tr>
                <th>Esprit</th>
                <td>{{ personnage.esprit }}</td>
            </tr>
            <tr>
                <th>Standard_de_vie</th>
                <td>{{ personnage.standardDeVie }}</td>
            </tr>
           
            <tr>
                <th>Sagesse</th>
                <td>{{ personnage.sagesse }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('personnage_index') }}">back to list</a>

    <a href="{{ path('personnage_edit', {'id': personnage.id}) }}">edit</a>

    {{ include('personnage/_delete_form.html.twig') }}
{% endblock %}