src/Entity/Amitie.php
<?php

namespace App\Entity;

use App\Repository\AmitieRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AmitieRepository::class)
 */
class Amitie
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="amities")
     */
    private $Ami1;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="amities")
     */
    private $Ami2;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAmi1(): ?User
    {
        return $this->Ami1;
    }

    public function setAmi1(?User $Ami1): self
    {
        $this->Ami1 = $Ami1;

        return $this;
    }

    public function getAmi2(): ?User
    {
        return $this->Ami2;
    }

    public function setAmi2(?User $Ami2): self
    {
        $this->Ami2 = $Ami2;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\ManyToMany(targetEntity=Partie::class, mappedBy="joueurs")
     */
    private $parties;

    /**
     * @ORM\OneToMany(targetEntity=Personnage::class, mappedBy="joueur")
     */
    private $personnages;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $pseudo;

    /**
     * @ORM\OneToMany(targetEntity=Amitie::class, mappedBy="Ami1")
     */
    private $amities;



    public function __construct()
    {
        $this->parties = new ArrayCollection();
        $this->personnages = new ArrayCollection();
        $this->amities = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection<int, Partie>
     */
    public function getParties(): Collection
    {
        return $this->parties;
    }

    public function addParty(Partie $party): self
    {
        if (!$this->parties->contains($party)) {
            $this->parties[] = $party;
            $party->addJoueur($this);
        }

        return $this;
    }

    public function removeParty(Partie $party): self
    {
        if ($this->parties->removeElement($party)) {
            $party->removeJoueur($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Personnage>
     */
    public function getPersos(): Collection
    {
        return $this->persos;
    }

    public function addPerso(Personnage $perso): self
    {
        if (!$this->persos->contains($perso)) {
            $this->persos[] = $perso;
            $perso->setUser($this);
        }

        return $this;
    }

    public function removePerso(Personnage $perso): self
    {
        if ($this->persos->removeElement($perso)) {
            // set the owning side to null (unless already changed)
            if ($perso->getUser() === $this) {
                $perso->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Personnage>
     */
    public function getPersonnages(): Collection
    {
        return $this->personnages;
    }

    public function addPersonnage(Personnage $personnage): self
    {
        if (!$this->personnages->contains($personnage)) {
            $this->personnages[] = $personnage;
            $personnage->setJoueur($this);
        }

        return $this;
    }

    public function removePersonnage(Personnage $personnage): self
    {
        if ($this->personnages->removeElement($personnage)) {
            // set the owning side to null (unless already changed)
            if ($personnage->getJoueur() === $this) {
                $personnage->setJoueur(null);
            }
        }

        return $this;
    }
    
    public function __toString()
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    /**
     * @return Collection<int, Amitie>
     */
    public function getAmities(): Collection
    {
        return $this->amities;
    }

    public function addAmity1(Amitie $amity): self
    {
        if (!$this->amities->contains($amity)) {
            $this->amities[] = $amity;
            $amity->setAmi1($this);
        }
        return $this;
    }
    public function addAmity2(Amitie $amity): self
    {
        if (!$this->amities->contains($amity)) {
            $this->amities[] = $amity;
            $amity->setAmi2($this);
        }
        return $this;
    }

    public function removeAmity1(Amitie $amity): self
    {
        if ($this->amities->removeElement($amity)) {
            // set the owning side to null (unless already changed)
            if ($amity->getAmi1() === $this) {
                $amity->setAmi1(null);
            }
        }

        return $this;
    }
    public function removeAmity2(Amitie $amity): self
    {
        if ($this->amities->removeElement($amity)) {
            // set the owning side to null (unless already changed)
            if ($amity->getAmi1() === $this) {
                $amity->setAmi1(null);
            }
        }

        return $this;
    }

}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email')
            ->add('roles')
            ->add('password')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Amitie;
use App\Entity\User;
use App\Form\RechercheAmisType;
use App\Form\UserType;
use App\Repository\AmitieRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/user')]
class UserController extends AbstractController
{
    #[Route('/', name: 'app_user_index', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }


    #[Route('/new', name: 'app_user_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }



    #[Route('/{id}/edit', name: 'app_user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }
    //Gère la recherche d'amis + l'ajout d'amis********************************************************
    #[Route('/{id}/{joueur_ami?null}', name: 'app_user_show', methods: ['GET', 'POST'])]
    public function show(User $user, Request $request,EntityManagerInterface $entityManager, $joueur_ami,UserRepository $userRepo): Response
    {
        $amis_du_joueur = null;
        //Partie recherche de joueurs//////////////////////
        $joueur_recherche='null';
        $form = $this->createForm(RechercheAmisType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            //Je vient chercher la value du form et fait un querybuilder pour voir si le pseudo existe
            $joueur_recherche = $userRepo->findPseudo($form["pseudo"]->getData());  
        }
        //Partie recherche de joueurs//////////////////////


        //Partie ajout d'amis//////////////////////
        if ($joueur_ami != 'null') {
            //$amis_du_joueur = $userRepo->find($joueur_ami)->getAmities();
            $nouvel_ami = $userRepo->find($joueur_ami);
            $amitie = new Amitie();
            $amitie->setAmi1($user)
                    ->setAmi2($nouvel_ami);
            $entityManager->persist($amitie);
            $entityManager->flush();
            return $this->redirectToRoute('app_user_show', ['id'=>$user->getId()], Response::HTTP_SEE_OTHER);
        }



        
        return $this->renderForm('user/show.html.twig', [
            'user' => $user,
            'form' => $form,
            'joueur_recherche'=>$joueur_recherche,
            'amis_du_joueur'=> $amis_du_joueur
        ]);
    }


    
    #[Route('/ami/delete/{amitie_id}', name: 'delet_friend', methods: ['GET', 'POST'])]
    public function deleteFriend(Request $request, $amitie_id, AmitieRepository $amitieRep, EntityManagerInterface $entityManager): Response
    {   
        $user = $this->getUser();

        $amitie = $amitieRep->find($amitie_id);

        $entityManager->remove($amitie);
        $entityManager->flush();
      
        return $this->redirectToRoute('app_user_show', ['id'=>$user->getId()], Response::HTTP_SEE_OTHER);
    }
  

  


  
}

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <h1>Modifier mon compte</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}
    {{ include('user/_delete_form.html.twig') }}
    
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <h1>User index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Email</th>
                <th>Roles</th>
                <th>Password</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
                <td>{{ user.password }}</td>
                <td>
                    <a href="{{ path('app_user_show', {'id': user.id}) }}">show</a>
                    <a href="{{ path('app_user_edit', {'id': user.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_user_new') }}">Create new</a>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1>Create new User</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('app_user_index') }}">back to list</a>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil{% endblock %}

{% block body %}
<div class="bigContent">
  <div class="side">
    
      <button id="perso" class="btn personnage">Personnages</button>
 
      <button id="amie" class="btn amie">Amie</button>
      
      <button id="partieShow" class="btn partie">Partie</button>
    
  </div>


  <div  class="contentPseudo">
    <h1>{{ app.user.pseudo }}</h1>

   
    <div id="personnage" class="contentPerso">
      <h3>Personnages </h3> 
        <br>
      {% for personnages in app.user.personnages %}
      
        <div class="Perso">
            {#  <a href="{{ path('personnage_show', {'id': personnages.id} ) }}">Voir la fiche complète du personnage</a> #}
            <div>nom personnage : {{personnages.nom }}</div>
            <div>class : {{personnages.classe }}</div> 
            <div>Parties jouées: {{personnages.partie|length}}</div>
        </div>
      {% endfor %}
    </div>
    <button class="newPerso"><a href="{{ path('personnage_new') }}">Créer un nouveau personnage</a></button>
  </div>
  <div id="partie" class="contentPartie">
      nombre de parties jouées: {{app.user.parties|length}}
    
    <button><a href="{{ path('app_partie_new') }}">Créer une nouvelle partie</a></button>
    <a href="{{ path('app_user_edit', {'id': user.id}) }}">edit</a>
    {{ include('user/_delete_form.html.twig') }}
      <br>
    <hr> 
    
    </div>
</div>
     
    
    
   

    {#   <h3>Ajouter un ami:</h3>  
      <br>
      {{form_start(form, {'action': path('app_user_show', {'id': app.user.id}), 'method': 'POST'})}}
      {{ form_row(form) }}
      <button type="submit">Rechercher</button>
      {{ form_end(form) }}
      {% set deja_ami = null %} #}

     {#  {% if joueur_recherche != 'null'%} #} {# Si il y a une recherche de pseudo #}  
          {#  {% if joueur_recherche and joueur_recherche.pseudo != app.user.pseudo  %} #} {# Si le pseudo existe et est différent de celui du user #}
{#               <b>{{joueur_recherche.pseudo}}</b>
              {% for amis in app.user.amities %}
                  {% if amis.Ami2.id == joueur_recherche.id %}
                    {% set deja_ami = true %}
                  {% endif %} 
              {% endfor %}
              
              {% if deja_ami %}
                Vous etes déjà amis !
              {% else %}
                <button>
                  <a href="{{ path('app_user_show', {'id': user.id, 'joueur_ami':joueur_recherche.id}) }}">
                    Ajouter
                  </a>
                </button>
              {% endif %} #}

             
 {#        {% else %}
          Pas de joueur trouvé
        {% endif %}
      {% endif %}
      
      <hr>
      <br>
      <h3>Mes amis:</h3>
      <ul>
       #}
     {#  {% for amis in app.user.amities %}
         <li>{{ amis.ami2.pseudo }}</li>
      {% endfor %}
      </ul> #}
   
    

{% endblock %}